# Your Website Title
title: Moh Husni Mubaraq

# Your Website URL
url: 'http://whoishusni.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Moh Husni Mubaraq
tagline: Android Developer, Game Developer
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: Android Developer, Game Developer
description_tiny: 'Meditate | Study | Work | Coding'
email: mohhusnimubaraq@gmail.com
website: whoishusni.github.io # do not add http://
linkedin: https://www.linkedin.com/in/moh-husni-mubaraq-b504831a0/
github: whoishusni
twitter: '#'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm