# Your Website Title
title: Moh Husni Mubaraq

# Your Website URL
url: 'http://whoishusni.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Mohammad Husni Mubaraq
tagline: Android Developer, Game Developer
pic: profile.jpg # profile.png can be found at /assets/images/profile.png
description: Person Who Write Code
description_tiny: 'Meditate | Study | Work | Coding'
# email: mohhusnimubaraq@gmail.com
# website: whoishusni.github.io # do not add http://
# linkedin: moh-husni-mubaraq-b504831a0
# github: whoishusni
# dicoding: whoishusni

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
